image: lycantropos/cmake:latest
stages:
  - build
  - generate

variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - CMakeFiles
    - CMakeCache.txt
    - cmake_install.cmake

build-programs:
  stage: build
  script:
    - cmake .
    - cmake --build . --use-stderr
  artifacts:
    paths:
      - bin/*
  only:
    - master
    - tags

generate-images:
  stage: generate
  script:
    - cmake .
    - make run_all
  artifacts:
    name: 'thumbnails-$CI_COMMIT_REF_SLUG'
    paths:
      - bin/*.ppm
  only:
    - master
    - tags