image: lycantropos/cmake:latest
stages:
  - build
  - generate
before_script:
  - apt-get update && apt-get upgrade
  - apt-get install --no-install-recommends libgraphicsmagick1-dev libmagick++-dev

variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - CMakeFiles
    - CMakeCache.txt
    - cmake_install.cmake
    - ext
    - cxxopts

build-programs:
  stage: build
  script:
    - cmake .
    - cmake --build . --use-stderr
  artifacts:
    paths:
      - bin/*
  only:
    - master
    - tags

generate-images:
  stage: generate
  script:
    - cmake .
    - make thumbnails
  artifacts:
    name: 'thumbnails-$CI_COMMIT_REF_SLUG'
    paths:
      - bin/*.png
    expire_in: 30 years
  only:
    - master
    - tags