name: C/C++ Cmake

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: cmake .
    - name: make
      run: cmake --build . --use-stderr
